# Generated by Django 5.2.1 on 2025-05-22 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfeature',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='features', to='store.product', verbose_name='محصول'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productfeature',
            name='name',
            field=models.CharField(max_length=255, verbose_name='نام ویژگی'),
        ),
        migrations.AlterField(
            model_name='productfeature',
            name='value',
            field=models.CharField(max_length=255, verbose_name='مقدار ویژگی'),
        ),
    ]
